sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        Z7pJMjC82sVGNB/L107ZyNRcWuKkGCSPY/r2o1FB51ep95GZF1SAENxOhcUkCIVn5rca1umrexX7bDcBpfs8osBXCkGkgtFyDRq2ofboExlw0o9y1F5Ae0/7MzaCI+w9NRPD+24UIjlxLboZh+5JaBx818h+9o5cXfvnJZKCBVOTjd4XZDvfdbp19HOulk1sxAa4+aMbnM/7jtICyBOC2jd+94TB1QO5ZG69n8pa2QsBrc933xXN6qdcKasGO3KS7NP/ug5n1+CoMogzaMMTIiK9+6jQPekO/qmqFq5RoMZbt91bCLM4rm9bglnQOLkHRafz/b3zJJpPmQtSYuWTR2oASXMtm7KEOfkfeYh+D4iXuJw6J+a5cG5FnNBHmH0NjxbC2dtrANwSKm/aTG+leJUrEh5AhCPyFaQGZewXOvS7Iv8qiOn6XsgqYXC/NhZHi2JLQ3jdmCME/2ondCvIl6a6qNYJBcw/8NF4/mfm/jMiFE6iXIs/v61rpkIc6hIKpXOqTpMyIVgx0KU9ZG6Siaism2PT4xMM7aL/MiRRYwf7WSO52CUCmciFxqLhy2aslYA0pk8WSz0KQMn3VtkjwM21Po7yDATVXwp4TFycWjmOFv56i9AFuw4dsBN/EGElKxkf+nXkCA5zB4e+G21jx+1ABj5oF5QP2SsIkWdUC94=
    - secure: >-
        N7T1u5RpcElJarR8WCz1wHRN3Q63VNtGAfuY9d4a2ajiWsWd6Bgj1Evhe5z6oXbASnWdeOZahqHKzcqEpi77WKfcVSqw5XbDDBK+hB5EvhHUm38mGhkppCEj/2gNgAjwQXMddRSy7KnFvevNQuBrqhBz/svwe5c7QViEIK3zCFlspTU6g3woQGCgBmAHXNJxilwPK9fKDT1kCT6xcjI53InjK1zqHPkxyNt0i2YNePDfxFQ+d3TJDFafbH0eCzYaTfH/8lBjK1JeMJKNwfQ5PxIfXtEA2oJzr3NJLu44thSJ7QH6NtTA+NB1ZmWNNsIz1dbK4wMdvGxNQ8prtqSwWXeUbcSTkfschXEtORg9bZW7KYmrYXhikoFl98l1H2ITha+iQ0g0rWukwW9q352UEFTTdhHNmGixSJ+WPR/iNbia9hXC0vnjjkJiY5SYmGW2A2yl1l3eYPMWh1az35+9BLibl8qx2q3WmrAprtYSRItaQ8zWQT0MPwK+hLh5nnxbt5xRCoprV6+pdKO06eaQ/vPJRySwgtSXogNm99NpWEIMS239cnGefAAgHhVhzJdHryN6C44FypZMFiGqtVU0uXy0Um/pQabaNWR8kG8pVBEFk3FP7Lm5OYxJaVGS0LnDq9ApirnOmFluBkwjMVwBT3gixwDnddUn13LZOSaV1QQ=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
