sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        JNwZEwDBE91N8iND/e7K6af5RLY2CWegOV/f159wBLhVotTaxRl/hZVlgl9Wsywhp57KrVjFWhEPDfwnjcPUsL5Ifih5OdbcQBBqh0i9MHd8KhgsIKL+y3CWHrQAq5tdg9AhHjIrSmAbSRx+wg0GyQIGTqdSYA5+Y/4zDrmlKJIcpV/UvPmovYIzIxefIZz/Do6/5XLIG7k/EQir0jLzcZoG6DcD1CZ7QgzPFrnvjeONV9EudmUwn2GugaCoI2EMO80e6DJu2FSLISTofosQiphBwW1qV1Y6a2PYnfjkq9OPxTyp5yngi7HHSd2E69ZDpBbkGIYK1kwCZGsK7mnpoNVj8L2y/nUPcZVdasKcUhM78q9e/qWBrWfEhvm8uBPn0VVWWgXv4iKr8XrZLokjxcj4l8LqZGtuTBEVROnlMn7DpJpozuoFiT3TLAi7NIlXbsZpoKCw40YONeulTvAfj04K8tvP+B2vKbYV5qrxA8IFHFB1n+kzy/LV8b5BwJMjDbM9aUH/cG3IvgcM4IqlX7K0tdPpIhtsNO5jMX/9delYEKW7/pf8vJC+JlZsseNLDhfSclWRdM7SO5yTc69soLuR39kJK2TO14yDt0K9pdV+4ILG13RqHOeHgv35fbXF29EOcqPL439UXbKLNhS4VsTYQbkY5nt/TvXO+K9W4tQ=
    - secure: >-
        Af2IeBMYbfwGXDHGL2cEvguoWQpy4a7Aw4KhQFEQMff7sH9q4UFdyZlLqiEQQnCW6MAbNz+33twOzi/gQLbKAX9i0k4euold4kamRsV2QopfOOVRjF1uOioY8E0ylqTu0d5XapfHWRGR5lHmgmRQPEm6z+K9ryNlXVmy2q0CvwVVqZuCuhjjc3MrBtOEGhK3B7ku+hWI8JjYD7UWxZH4kuo7XQooSZMKNid/8PYy7f6B70hpTbmC+Vsma7ysUeOxcIzYM6l5E14IqPCzGrqNMCdUoVu/9V4XG2VxL9TIE2uKiATU9su9d+oK4SI9EbsT18LEGAxNevynp/7wHC8JXi9146dWRkaqTc3L/rAHxPL1lUvp4k3qHTdt4LIZT4+19gRifuBXnvjTNmXf5cwSi32WC1LrQlyPrBQ9gPQdftAkgF8aZKPBLEwJZiD+7UbpzgrTlDBsZuXYgxoTngklyrsSODE0Et1CmGCa0j30NNTx9hXaxerkj60sWqZabxwKsBVObHQdTuiW+7x7IDc+jYzYefIj0Y/wpgda4QTaC/wdLzErryL+0qufD4PLXdfxk3SWWIHtbr6+y3TaPSBzC67FJbrLXTWx1iP92vGC7ZbkRyrkGoqWK48yEszAa9PsS8dbuB3LHExsvU0/UKt2yTHH93W2f0n5aX0C8erfOaA=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
